OnlineCourseReg/urls.py
from django.contrib import admin
from django.urls import path,include
from myadmin import urls as admin_url
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView
from student import urls as student_url

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('myadmin/',include(admin_url)) ,
    path('', TemplateView.as_view(template_name="index.html"), name="index"),
    path('student/',include(student_url)),
]

# static function will return a URL pattern for serving files in debug mode


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

myadmin/urls.py
from django.urls import path
from myadmin import views

app_name = 'myadmin'
urlpatterns = [
    path('',views.admin_login,name="admin_login"),
    path('admin_login_check/',views.admin_login_check,name="admin_login_check"),
    path('login_success/',views.admin_login_success,name="login_success"),
    path('admin_logout/',views.admin_logout,name="admin_logout"),

    # Admin Course Operations
    path('add_course/',views.add_course,name = "add_course"),
    path('save_course_type/',views.add_course,name = "save_course_type"),
    path('save_course/',views.save_course,name = "save_course"),

    # Admin Schedule Operations
    path('schedule_new_batches/',views.ScheduleNewBatch.as_view(),name = "schedule_new_batches"),
    path('view_scheduled_batches/',views.ViewScheduledBatches.as_view(),name = "view_scheduled_batches"),
    path('update_batch/<int:pk>',views.UpdateSchedule.as_view(),name = "update_batch"),
    path('delete_batch/<int:pk>',views.delete_batch,name ="delete_batch"),

    # Admin Faculty operation
    path('faculty/',views.FacultyOperation.as_view(),name ="faculty"),
]

student/urls.py
from django.urls import path
from student import views

app_name = 'student'
urlpatterns = [
    # Student Register
    path('register/',views.Register.as_view(),name = "register"),
    path('login/',views.Login.as_view(),name = "login"),
    path('login_success/',views.login_success,name = "login_success"),
    path('logout/',views.student_logout,name = "logout"),

    # New Batch Enrolement

    path('view_new_batches/',views.view_new_batches,name = "view_new_batches"),
    path('enroll_student/<int:batch_id>/<int:mobile>/',views.enroll_student,name = "enroll_student"),
    path('enrolled_batches/',views.enrolled_batches,name = "enrolled_batches"),
    path('cancel_registration/<int:batch_id>',views.cancel_registration,name = "cancel_registration"),
]

student/models.py
from django.db import models
from myadmin.models import CommonModel

#Student Registration Model


class Student(CommonModel):
    pic = models.ImageField(blank=True, upload_to="student_pics/")
    def __str__(self):
        return self.first_name

class BatchEnrollement(models.Model):

    mobile = models.BigIntegerField()
    batch_id = models.IntegerField()

student/forms.py
from django import forms
from .models import Student

# Student Register Form


class StudentRegister(forms.ModelForm):
    class Meta:
        model = Student
        fields = "__all__"


# Student login form


class StudentLoginForm(forms.ModelForm):
    """Admin Login Form"""
    class Meta:
        model = Student
        fields = ('username','password')
        widgets = {
            "username":forms.TextInput(
                attrs={
                    "class":"form-control-lg",
                    "placeholder":"Enter Your Username"
                }
            ),
            "password":forms.PasswordInput(
                attrs={
                    "class":"form-control-lg",
                    "placeholder":"Enter Your Password"
                }
            )
        }

student/views.py
from django.shortcuts import render,redirect
from django.views.generic.base import View
from .forms import *
from  .models import *
from myadmin.models import ScheduleBatch
from django.contrib import messages

# Create your views here.


class Register(View):
    """ Performs Student Adding And Saving Operation"""
    def get(self,request):
        """Showing Student Registration Form"""
        context = {
            "StudentRegister":StudentRegister()
        }
        return render(request,"student/register.html",context=context)

    def post(self,request):
        """Saving Student Details"""
        sr = StudentRegister(request.POST,request.FILES)
        if sr.is_valid():
            sr.save()
            messages.success(request,"Registered Successfully")
            return redirect('student:register')
        else:
            return render(request,"student/register.html",context={"StudentRegister":sr})


class Login(View):
    """ Performs Student Login and Session Creation """

    def get(self, request):
        """Showing Student Login Form"""
        context = {
            "StudentLoginForm": StudentLoginForm()
        }
        return render(request, "student/login.html", context=context)

    def post(self, request):
        """Performs Session Creation on Successful Login"""
        username = request.POST['username']
        password = request.POST['password']
        try:
            obj = Student.objects.get(username=username, password=password)
            request.session['status'] = obj.email
            return redirect('student:login_success')
        except Student.DoesNotExist:
            messages.error(request, "Invalid Credentials")
            return redirect('student:login')


def login_success(request):
    try:
        obj = Student.objects.get(email= request.session['status'])
        return render(request,"student/login_success.html",context={"student_data":obj})
    except KeyError:
        return redirect('student:login')


def student_logout(request):
    del request.session['status']
    return redirect('student:login')

# New Batch Enrolement


def view_new_batches(request):
    try:
        context = {
            "ScheduleBatch":ScheduleBatch.objects.all(),
            "student_data":Student.objects.get(email= request.session['status'])
         }
        return render(request,"student/view_new_batches.html",context=context)
    except KeyError:
        return redirect('student:login_success')


def enroll_student(request,batch_id,mobile):
    BatchEnrollement(batch_id=batch_id,mobile=mobile).save()
    messages.success(request,"Entrolled Successfully")
    return redirect('student:view_new_batches')


def enrolled_batches(request):
    context = {
        "BatchEnrollement": [
            [batch.batch_id,s.course_name,s.faculty_name,s.start_date,s.time,s.duration,s.batch_type,s.fee]
            for batch in BatchEnrollement.objects.all() for s in ScheduleBatch.objects.all() if batch.batch_id == s.idno
        ],
        "BE":BatchEnrollement.objects.all()
    }
    print(context["BatchEnrollement"])

    return render(request,"student/enrolled_batches.html",context=context)


def cancel_registration(request,batch_id):
    BatchEnrollement.objects.get(id=batch_id).delete()
    messages.success(request,"Registration Cancelled Successfully")
    return redirect('student:enrolled_batches')

templates/student/enrolled_batches.html
{% extends 'base.html' %}
{% block title%}Enrolled Batches{% endblock title %}


{% block common %}

    {% if request.session.status %}

        {% include 'student/navbar.html' %}
        <div class="container-fluid my-5">
        <div class="row text-center">
            <div class=" col-12 bg-light p-4">
                <h3 class="bg-success">Enrolled Batches | Course Schedule | Batch Timings</h3>

                    <table class="table table-hover table-responsive-lg">
                        <thead class="thead-light">
                            {% for msg in messages %}
                            <tr>
                            <th colspan="9"><label class="alert alert-success">{{ msg }}</label></th>
                            </tr>
                            {% endfor %}
                            <tr>
                                <th rowspan="2">Enroll</th>

                            </tr>

                            <tr>
                                <th>Batch ID</th>
                                <th>Enrolled Courses</th>
                                <th>Faculty</th>
                                <th>Start Date</th>
                                <th>Time</th>
                                <th>Duration</th>
                                <th>Mode</th>
                                <th>Fee</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td rowspan="{{ BE.values_list.count|add:'2' }}">


                                    <table>
                                        {% for x in BE %}
                                            <tr>
                                                <td><a  href="{% url 'student:cancel_registration' x.id %}" class="btn btn-link btn-warning">Cancel</a></td>
                                            </tr>
                                        {% endfor %}

                                    </table>
                                </td>
                            </tr>
                            {% for batch in BatchEnrollement %}
                            <tr>
                                {% for field in batch %}

                                    <td>{{ field }}</td>
                                {% endfor %}
                            </tr>
                            {% endfor %}

                        </tbody>
                        <tfoot>

                        </tfoot>
                    </table>

            </div>
        </div>
    </div>

    {% else %}


        {{ block.super }}
        <div class="jumbotron jumbotron-fluid text-center">
            <h2 class="display-4">Session Expired !!!</h2>
            <a href="{% url 'student:login' %}" class="btn btn-warning">Login Again</a>
        </div>

    {% endif %}

{% endblock common %}

templates/student/login.html
{% extends 'base.html' %}
<!--Page Title Here-->
{% block title %}Student_Login{% endblock title %}

<!--Page Body Start Here-->
{% block body %}

    {% include 'navbar.html' %}
    <div class="container my-5">
        <div class="row text-center">
            <div class="offset-md-3 col-md-6 bg-light p-4">
                <h3 class="bg-success">STUDENT LOGIN </h3>
                <form class="form-group my-4 p-4" action="{% url 'student:login' %}" method="post">
                    {% csrf_token %}
                    {{ StudentLoginForm.as_p }}
                    <div class="btn-group btn-toolbar my-3 p-4">
                        <button type="submit" class="btn btn-outline-success">LOGIN</button>
                        <button type="reset" class="btn btn-outline-danger">RESET</button>
                    </div>
                    {% for msg in messages %}
                        <label class="alert alert-danger">{{ msg }}</label>
                    {% endfor %}

                </form>
            </div>
        </div>
    </div>


{% endblock body %}
<!--Page Body End Here-->

templates/student/login_success.html
{% extends 'base.html' %}
{% load static %}

{% block title%}Student{% endblock title %}


{% block common %}

    {% if request.session.status %}

        {% include 'student/navbar.html' %}
        <div class="container-fluid">
            <div class="row text-center">
                <div class="offset-2 col-8">
                    <h1>Welcome To {{ student_data.first_name }}</h1>
                    {% if student_data.pic %}
                        <img src="{{ student_data.pic.url }}" class="h-55 w-50">
                    {% endif %}
                </div>
            </div>
        </div>

    {% else %}


        {{ block.super }}
        <div class="jumbotron jumbotron-fluid text-center">
            <h2 class="display-4">Session Expired !!!</h2>
            <a href="{% url 'student:login' %}" class="btn btn-warning">Login Again</a>
        </div>

    {% endif %}

{% endblock common %}

templates/student/navbar.html
<!--Navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-info">
            <div >
                <a class="navbar-brand" href="{% url 'student:login_success' %}">E-Learn</a>
            </div>
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarContent">
                <span class="navbar-toggler-icon"></span>
            </button>

            <ul class="collapse navbar-nav navbar-collapse" id="navbarContent">

                <li class="nav-item"><a class="nav-link">{{ student_data.username|capfirst }}</a></li>
                <li class="nav-item"><a href="{% url 'student:view_new_batches' %}" class="nav-link">New Batch</a></li>
                <li class="nav-item"><a href="{% url 'student:enrolled_batches' %}" class="nav-link">View Enrolled Batch</a></li>
                <li class="nav-item"><a class="nav-link">Courses Available</a></li>
                <li class="nav-item"><a href="{% url 'student:logout' %}" class="nav-link">Logout</a></li>

            </ul>
        </nav>

templates/student/register.html
{% extends 'base.html' %}
<!--Page Title Here-->
{% block title %}Register-Student{% endblock title %}

<!--Page Body Start Here-->
{% block body %}

    {% include 'navbar.html' %}
    <div class="container my-5">
        <div class="row text-center">
            <div class="offset-md-3 col-md-6 bg-light p-4">
                <h3 class="bg-success">Student Register</h3>
                {% for msg in messages %}
                    <label class="alert alert-success">{{ msg }}</label>
                {% endfor %}
                <form class="form-group my-4 p-4" action="{% url 'student:register' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ StudentRegister.as_p }}
                    <div class="btn-group btn-toolbar my-3 p-4">
                        <button type="submit" class="btn btn-outline-success">REGISTER</button>
                        <button type="reset" class="btn btn-outline-danger">RESET</button>
                    </div>
                </form>
            </div>
        </div>
    </div>


{% endblock body %}
<!--Page Body End Here-->

templates/student/view_new_batches.html
{% extends 'base.html' %}
{% block title%}View New Batch{% endblock title %}


{% block common %}

    {% if request.session.status %}

        {% include 'student/navbar.html' %}
        <div class="container-fluid my-5">
        <div class="row text-center">
            <div class="offset-1 col-10 bg-light p-4">
                <h3 class="bg-success">New Batches | Course Schedule | Batch Timings</h3>

                    <table class="table table-hover table-striped table-responsive-lg">
                        <thead class="thead-light">
                            {% for msg in messages %}
                            <tr>
                            <th colspan="9"><label class="alert alert-success">{{ msg }}</label></th>
                            </tr>
                            {% endfor %}

                            <tr>
                                <th>Course</th>
                                <th>Faculty</th>
                                <th>Type</th>
                                <th>Duration</th>
                                <th>Fee</th>
                                <th>Date</th>
                                <th>Time</th>
                                <th>Enroll</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for batch in ScheduleBatch %}
                            <tr>
                                <td>{{ batch.course_name }}</td>
                                <td>{{ batch.faculty_name }}</td>
                                <td>{{ batch.batch_type }}</td>
                                <td>{{ batch.duration }}</td>
                                <td>{{ batch.fee }}</td>
                                <td>{{ batch.start_date }}</td>
                                <td>{{ batch.time }}</td>
                                <td><a href="{% url 'student:enroll_student' batch.idno student_data.mobile %}" class="btn btn-primary">Enroll</a></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                        <tfoot></tfoot>
                    </table>


            </div>
        </div>
    </div>

    {% else %}


        {{ block.super }}
        <div class="jumbotron jumbotron-fluid text-center">
            <h2 class="display-4">Session Expired !!!</h2>
            <a href="{% url 'student:login' %}" class="btn btn-warning">Login Again</a>
        </div>

    {% endif %}

{% endblock common %}