OnlineCourseReg/urls.py
from django.contrib import admin
from django.urls import path,include
from myadmin import urls as admin_url
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView
from student import urls as student_url

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('myadmin/',include(admin_url)) ,
    path('', TemplateView.as_view(template_name="index.html"), name="index"),
    path('student/',include(student_url)),
]

# static function will return a URL pattern for serving files in debug mode


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

myadmin/urls.py
from django.urls import path
from myadmin import views

app_name = 'myadmin'
urlpatterns = [
    path('',views.admin_login,name="admin_login"),
    path('admin_login_check/',views.admin_login_check,name="admin_login_check"),
    path('login_success/',views.admin_login_success,name="login_success"),
    path('admin_logout/',views.admin_logout,name="admin_logout"),

    # Admin Course Operations
    path('add_course/',views.add_course,name = "add_course"),
    path('save_course_type/',views.add_course,name = "save_course_type"),
    path('save_course/',views.save_course,name = "save_course"),

    # Admin Schedule Operations
    path('schedule_new_batches/',views.ScheduleNewBatch.as_view(),name = "schedule_new_batches"),
    path('view_scheduled_batches/',views.ViewScheduledBatches.as_view(),name = "view_scheduled_batches"),
    path('update_batch/<int:pk>',views.UpdateSchedule.as_view(),name = "update_batch"),
    path('delete_batch/<int:pk>',views.delete_batch,name ="delete_batch"),

    # Admin Faculty operation
    path('faculty/',views.FacultyOperation.as_view(),name ="faculty"),
]

student/urls.py
from django.urls import path
from student import views

app_name = 'student'
urlpatterns = [
    # Student Register
    path('register/',views.Register.as_view(),name = "register"),
    path('login/',views.Login.as_view(),name = "login"),
    path('login_success/',views.login_success,name = "login_success"),
    path('logout/',views.student_logout,name = "logout"),

    # New Batch Enrolement

    path('view_new_batches/',views.view_new_batches,name = "view_new_batches"),
    path('enroll_student/<int:batch_id>/<int:mobile>/',views.enroll_student,name = "enroll_student"),
    path('enrolled_batches/',views.enrolled_batches,name = "enrolled_batches"),
    path('cancel_registration/<int:batch_id>',views.cancel_registration,name = "cancel_registration"),
]

templates/base.html
<!doctype html>

{% load static %}

<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">

    <title>{% block title %}E-Learn{% endblock title %}</title>

    <!--Embeded Style-->
    {% block style %}
        <style>
            body{
                font-family: 'Indie Flower', cursive;
            }
        </style>
    {% endblock style %}


  </head>


  <body class="container-fluid">


  {% block common %}


    <section id="header">
            <h1 class="text-center bg-info">
                <a href="{% url 'index' %}" class="btn-link  text-white text-decoration-none">E-Learn</a>
            </h1>
    </section>


  {% endblock common %}



  {% block body %}

  {% endblock body %}




    <!--Footer Section Start Here-->

    <section class="container-fluid">
        <div class="row bg-info">
            <div class="offset-4 col-6">
                <strong class="text-center text-white">
                    <i>&copy;Copyrights | 2020 | By Kisan Kumar Behera</i>
                </strong>
            </div>
        </div>
    </section>

    <!--Footer Section End Here-->



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.bundle.js' %}"></script>
  </body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}

<!--Page Title Here-->
{% block title %}E-Learn-Home{% endblock title %}

<!--Page Body Start Here-->
{% block body %}

    {% include 'navbar.html' %}
    <div class="container-fluid">
            <div class="row text-center">
                <div class="offset-2 col-8">
                    <h1>Welcome To E-Learn</h1>
                    <img src="{% static 'images/E-learn.png' %}" class="w-100">
                </div>
            </div>
    </div>


{% endblock body %}
<!--Page Body End Here-->

templates/navbar.html
<!--Navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-info">
            <div >
                <a class="navbar-brand" href="#">E-Learn</a>
            </div>
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarContent">
                <span class="navbar-toggler-icon"></span>
            </button>

            <ul class="collapse navbar-nav navbar-collapse" id="navbarContent">
                <li class="nav-item"><a href="{% url 'student:register' %}" class="nav-link">Register</a></li>
                <li class="nav-item"><a href="{% url 'student:login' %}" class="nav-link">Login</a></li>
                <li class="nav-item"><a href="#" class="nav-link">New Batches</a></li>
                <li class="nav-item"><a href="#" class="nav-link">Contact Us</a></li>
            </ul>
        </nav>