OnlineCourseReg/urls.py
from django.contrib import admin
from django.urls import path,include
from myadmin import urls as admin_url
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView
from student import urls as student_url

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('myadmin/',include(admin_url)) ,
    path('', TemplateView.as_view(template_name="index.html"), name="index"),
    path('student/',include(student_url)),
]

# static function will return a URL pattern for serving files in debug mode


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

myadmin/urls.py
from django.urls import path
from myadmin import views

app_name = 'myadmin'
urlpatterns = [
    path('',views.admin_login,name="admin_login"),
    path('admin_login_check/',views.admin_login_check,name="admin_login_check"),
    path('login_success/',views.admin_login_success,name="login_success"),
    path('admin_logout/',views.admin_logout,name="admin_logout"),

    # Admin Course Operations
    path('add_course/',views.add_course,name = "add_course"),
    path('save_course_type/',views.add_course,name = "save_course_type"),
    path('save_course/',views.save_course,name = "save_course"),

    # Admin Schedule Operations
    path('schedule_new_batches/',views.ScheduleNewBatch.as_view(),name = "schedule_new_batches"),
    path('view_scheduled_batches/',views.ViewScheduledBatches.as_view(),name = "view_scheduled_batches"),
    path('update_batch/<int:pk>',views.UpdateSchedule.as_view(),name = "update_batch"),
    path('delete_batch/<int:pk>',views.delete_batch,name ="delete_batch"),

    # Admin Faculty operation
    path('faculty/',views.FacultyOperation.as_view(),name ="faculty"),
]

faculty/models.py
from django.db import models
# from myadmin.models import CommonModel


# Faculty Model


class Faculty(models.Model):
    '''Faculty Model'''
    idno = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    username = models.CharField(max_length=30, unique=True)
    password = models.CharField(max_length=15)
    mobile = models.BigIntegerField(unique=True)
    email = models.EmailField(unique=True)
    address = models.TextField()
    joined_date = models.DateField(auto_now=True)
    pic = models.ImageField(blank=True, upload_to="faculty_pics/")
    def __str__(self):
        return self.first_name

myadmin/models.py
from django.db import models
from django.utils import timezone

from faculty.models import Faculty

# Common Register Model


class CommonModel(models.Model):
    '''Common Register Model'''
    idno = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    username = models.CharField(max_length=30, unique=True)
    password = models.CharField(max_length=15)
    mobile = models.BigIntegerField(unique=True)
    email = models.EmailField(unique=True)
    address = models.TextField()


    class Meta:
        abstract = True


# Admin Login Model


class AdminLoginModel(CommonModel):
    '''Admin Model'''
    pic = models.ImageField(blank=True, upload_to="admin_pics/")

# Course Type Model


class CourseType(models.Model):
    '''Different Trending Types Of Courses'''
    idno = models.AutoField(primary_key=True)
    name = models.CharField(max_length=40, unique=True)

    def __str__(self):
        return self.name

# Course Model


class Course(models.Model):
    '''Course Model'''
    idno = models.AutoField(primary_key=True)
    name = models.CharField(max_length=40,unique=True)
    pic = models.ImageField(blank=True, upload_to="course_pics/")
    type = models.ManyToManyField(CourseType)
    def __str__(self):
        return self.name

# Schedule Batch Model


class ScheduleBatch(models.Model):
    idno = models.AutoField(primary_key=True)
    course_name = models.ForeignKey(Course,on_delete=models.CASCADE)
    faculty_name = models.ForeignKey(Faculty,on_delete=models.CASCADE)
    batch_type = models.CharField(max_length=50)
    duration = models.IntegerField()
    fee = models.FloatField()
    start_date = models.DateField(default=timezone.now)
    time = models.TimeField()

    def __str__(self):
        return self.course_name.name

faculty/forms.py
# Faculty Form


from django import forms
from .models import Faculty



class FacultyForm(forms.ModelForm):


    class Meta:
        model = Faculty
        fields = "__all__"
        widgets = {
            "password":forms.PasswordInput(
                attrs={
                    "placeholder":"Enter Password",
                    "class":"form-control-lg",
                }
            ),
            "first_name":forms.TextInput(
                attrs={
                    "placeholder":"First Name",
                    "class":"form-control-lg",
                }
            ),
            "last_name": forms.TextInput(
                attrs={
                    "placeholder": "Last Name",
                    "class": "form-control-lg",
                }
            ),
            "username": forms.TextInput(
                attrs={
                    "placeholder": "Enter Username",
                    "class": "form-control-lg",
                }
            ),
            "mobile": forms.NumberInput(
                attrs={
                    "placeholder": "10 Digit mobile",
                    "class": "form-control-lg",
                    "type":"tel",
                }
            ),
            "email": forms.EmailInput(
                attrs={
                    "placeholder": "Email ID",
                    "class": "form-control-lg",
                }
            ),
            "address": forms.Textarea(
                attrs={
                    "placeholder": "Address",
                    "class": "form-control",
                }
            ),
        }

myadmin/forms.py
from django import forms
from .models import *

# Admin form


class AdminLoginForm(forms.ModelForm):
    """Admin Login Form"""
    class Meta:
        model = AdminLoginModel
        fields = ('username','password')
        widgets = {
            "username":forms.TextInput(
                attrs={
                    "class":"form-control-lg",
                    "placeholder":"Enter Your Username"
                }
            ),
            "password":forms.PasswordInput(
                attrs={
                    "class":"form-control-lg",
                    "placeholder":"Enter Your Password"
                }
            )
        }


# CourseType Form

class CourseTypeForm(forms.ModelForm):
    """CourseType Form"""
    class Meta:
        model = CourseType
        fields = "__all__"
        exclude = ("idno",)
    name = forms.CharField(
        label="Course Type",
        widget=forms.TextInput(
            attrs={
                "class":"form-control-lg",
                "placeholder":"Course Type Name"
            }
        )
    )
    pic = forms.ImageField(
        label="Logo",
        required=False,
        widget=forms.FileInput(
            attrs={
                "class":"form-control-md",
            }
        )
    )

# Course Form


class CourseForm(forms.ModelForm):
    """Course Form"""
    class Meta:
        model = Course
        fields = "__all__"
        exclude = ("idno",)

    name = forms.CharField(
        label= 'Course Name',
        widget=forms.TextInput(
            attrs={
                "class":"form-control-lg",
                "placeholder":"Course Name"
            }
        )
    )

    pic = forms.ImageField(
        label="Image",
        required=False,
        widget=forms.FileInput(
            attrs={
                "class": "form-control-md",
            }
        )
    )

class ScheduleBatchForm(forms.ModelForm):
    BATCH_CHOICES = (
        ("Class Room Training","Class Room Training"),
        ("Online Training","Online Training"),
        ("Weekend Training","Weekend Training"),
        ("Special Batch","Special Batch"),
        ("Job Placement","Job Placement")
    )
    class Meta:
        model = ScheduleBatch
        fields = "__all__"
        exclude = ("idno",)
        widgets ={
            "time":forms.TimeInput(
                attrs={
                    "type":"time",
                    "class":"form-control-lg"
                },
                                   ),
            "start_date":forms.DateInput(
                attrs={
                    "class":"form-control-lg",
                    "type":"date"
                },
            )
        }
    batch_type = forms.ChoiceField(
        choices=BATCH_CHOICES,
        label="Type",
        widget=forms.Select(
            attrs={
                "class":"form-control"
            }
        )
    )


    fee = forms.FloatField(
        widget=forms.NumberInput(
            attrs={
                "class": "form-control-lg",
                "step": 0.01,
                "min": 0
            }
        )
    )

faculty/views.py
from django.shortcuts import render

# Create your views here.

myadmin/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.views.generic import UpdateView

from .forms import *
from .models import AdminLoginModel,CourseType,Course
from django.contrib import messages
from django.views.generic.base import View
from faculty.forms import *
from django.urls import reverse_lazy


def admin_login(request):
    '''The FBV returns a HttpResponse with AdminLoginForm'''
    return render(request,template_name="myadmin/admin_login.html",context={'AdminLoginForm':AdminLoginForm()})

# Admin Login Check


def admin_login_check(request):
    username = request.POST['username']
    password = request.POST['password']
    try:
        obj = AdminLoginModel.objects.get(username=username,password=password)
        request.session['status'] = obj.mobile
        return redirect('myadmin:login_success')
    except AdminLoginModel.DoesNotExist:
        messages.error(request,"Invalid Credentials")
        return redirect('myadmin:admin_login')

# Admin Login Success


def admin_login_success(request):

    try:
        obj = AdminLoginModel.objects.get(mobile= request.session['status'])
        return render(request,"myadmin/login_success.html",context={"admin_data":obj})
    except KeyError:
        return render(request,"myadmin/login_success.html")

# Admin Logout


def admin_logout(request):
    del request.session['status']
    return redirect('myadmin:admin_login')


def add_course(request):
    if request.method == "POST":
        ctype = CourseTypeForm(request.POST,request.FILES)
        if ctype.is_valid():
            ctype.save()
            messages.success(request,"Course Type Successfully Saved")
            return redirect('myadmin:add_course')
        else:
            return render(request,"myadmin/add_course.html",context={"CourseTypeForm":ctype})
    else:
        try:
            obj = AdminLoginModel.objects.get(mobile=request.session['status'])
            # If There is Session
            context = {
                "admin_data": obj,
                "CourseTypeForm": CourseTypeForm(),
                "CourseForm": CourseForm(),
            }
            return render(request, "myadmin/add_course.html", context=context)

        # If No Session
        except KeyError:

            return render(request, "myadmin/add_course.html")


def save_course(request):
    if request.method == "POST":
        cf = CourseForm(request.POST,request.FILES)
        if cf.is_valid():
            cf.save()
            messages.success(request, "Course Successfully Saved")
            return redirect('myadmin:add_course')
        else:
            return render(request,"myadmin/add_course.html",context={'CourseForm':cf})


# Schedule New Batch


class ScheduleNewBatch(View):
    def get(self,request):
        context = {
            "ScheduleBatchForm": ScheduleBatchForm()
        }
        return render(request, "myadmin/schedule_new_batches.html", context=context)
    def post(self,request):
        sbf = ScheduleBatchForm(request.POST)
        if sbf.is_valid():
            sbf.save()
            messages.success(request,"New Batch Scheduled")
            return redirect('myadmin:schedule_new_batches')
        else:
            return render(request,"myadmin/schedule_new_batches.html",context={"ScheduleBatchForm":sbf})

class ViewScheduledBatches(View):
    def get(self,request):
        context = {
            "view":ScheduleBatch.objects.all()
        }
        return render(request,"myadmin/view_scheduled_batches.html",context=context)

class UpdateSchedule(UpdateView):
    template_name = "myadmin/update_batch.html"
    model = ScheduleBatch
    form_class = ScheduleBatchForm
    success_url = reverse_lazy("myadmin:view_scheduled_batches")

def delete_batch(request,pk):
    ScheduleBatch.objects.get(idno=pk).delete()
    messages.success(request,"Batch Deleted Successfully")
    return redirect('myadmin:view_scheduled_batches')


# Faculty Operation


class FacultyOperation(View):


    def get(self,request):
        context = {
            "FacultyForm":FacultyForm()
        }
        return render(request,"myadmin/faculty.html",context=context)


    def post(self,request):
        """Save Faculty Operation"""
        ff = FacultyForm(request.POST,request.FILES)
        if ff.is_valid():
            ff.save()
            messages.success(request,"Faculty Saved Successfully")
            return redirect("myadmin:faculty")
        else:
            context = {
                "FacultyForm": ff,
            }
            return render(request,"myadmin/faculty.html",context=context)

templates/myadmin/add_course.html
{% extends 'myadmin/base.html' %}
{% block title%}Success{% endblock title %}
{% block style %}

{% endblock style %}


{% block common %}

    {% if request.session.status %}

        {% include 'myadmin/navbar.html' %}
        <section id="course" class="container">
            <div class="row text-center my-5 p-4">

                {% for msg in messages %}
                    <div class="offset-3 col-6">
                        <label class="alert alert-success">{{ msg }}</label>
                    </div>
                {% endfor %}

                <!--Course-Type Form Start Here-->

                <div class="offset-1 col-5 bg-light p-4">
                    <h3 class="bg-warning text-info">Add Course-Type</h3>
                    <form class="form-group my-5" action="{% url 'myadmin:save_course_type' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ CourseTypeForm.as_p }}
                        <div class="btn-group btn-toolbar">
                            <button type="submit" class="btn btn-success">ADD</button>
                            <button type="reset" class="btn btn-danger">RESET</button>
                        </div>
                    </form>
                </div>

                <!--Course-Type Form End Here-->

                <!--Course Form Start Here-->

                <div class="offset-1 col-5 bg-light p-4">
                    <h3 class="bg-warning text-info">Add Course</h3>
                    <form class="form-group my-5" action="{% url 'myadmin:save_course' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ CourseForm.as_p }}
                        <div class="btn-group btn-toolbar">
                            <button type="submit" class="btn btn-success">ADD</button>
                            <button type="reset" class="btn btn-danger">RESET</button>
                        </div>
                    </form>
                </div>
                <!--Course Form End Here-->

            </div>
        </section>

    {% else %}


        {{ block.super }}
        <div class="jumbotron jumbotron-fluid text-center">
            <h2 class="display-4">Session Expired !!!</h2>
            <a href="{% url 'myadmin:admin_login' %}" class="btn btn-warning">Login Again</a>
        </div>

    {% endif %}

{% endblock common %}

templates/myadmin/admin_login.html
{% extends 'myadmin/base.html' %}
<!--Page Title Here-->
{% block title %}Admin_Login{% endblock title %}

<!--Page Body Start Here-->
{% block body %}


    <div class="container my-5">
        <div class="row text-center">
            <div class="offset-md-3 col-md-6 bg-light p-4">
                <h3 class="bg-success">ADMIN LOGIN </h3>
                <form class="form-group my-4 p-4" action="{% url 'myadmin:admin_login_check' %}" method="post">
                    {% csrf_token %}
                    {{ AdminLoginForm.as_p }}
                    <div class="btn-group btn-toolbar my-3 p-4">
                        <button type="submit" class="btn btn-outline-success">LOGIN</button>
                        <button type="reset" class="btn btn-outline-danger">RESET</button>
                    </div>
                    {% for msg in messages %}
                        <label class="alert alert-danger">{{ msg }}</label>
                    {% endfor %}

                </form>
            </div>
        </div>
    </div>


{% endblock body %}
<!--Page Body End Here-->

templates/myadmin/base.html
<!doctype html>

{% load static %}

<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">

    <title>{% block title %}admin{% endblock title %}</title>

    <!--Embeded Style-->
    {% block style %}
        <style>
            body{
                font-family: 'Indie Flower', cursive;
            }
        </style>
    {% endblock style %}


  </head>


  <body class="container-fluid">


  {% block common %}


    <section id="header">
            <h1 class="text-center bg-info">
                <a href="{% url 'index' %}" class="btn-link  text-white text-decoration-none">E-Learn</a>
            </h1>
    </section>


  {% endblock common %}



  {% block body %}

  {% endblock body %}




    <!--Footer Section Start Here-->

    <section class="container-fluid">
        <div class="row bg-info">
            <div class="offset-4 col-6">
                <strong class="text-center text-white">
                    <i>&copy;Copyrights | 2020 | By Kisan Kumar Behera</i>
                </strong>
            </div>
        </div>
    </section>

    <!--Footer Section End Here-->



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.bundle.js' %}"></script>
  </body>
</html>

templates/myadmin/faculty.html
{% extends 'myadmin/base.html' %}
{% block title%}Success{% endblock title %}
{% block style %}

{% endblock style %}


{% block common %}

    {% if request.session.status %}

        {% include 'myadmin/navbar.html' %}
        <section id="course" class="container">
            <div class="row text-center my-5 p-4">

                {% for msg in messages %}
                    <div class="offset-3 col-6">
                        <label class="alert alert-success">{{ msg }}</label>
                    </div>
                {% endfor %}

                <!--Faculty Form Start Here-->

                <div class="offset-1 col-4 bg-light p-4">
                    <h3 class="bg-warning text-info">Add Faculty</h3>
                    <form class="form-group my-5" action="{% url 'myadmin:faculty' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ FacultyForm.as_p }}
                        <div class="btn-group btn-toolbar">
                            <button type="submit" class="btn btn-success">ADD</button>
                            <button type="reset" class="btn btn-danger">RESET</button>
                        </div>
                    </form>
                </div>

                <!--Faculty Form End Here-->

                <!--View Faculty Start Here-->

                <div class="offset-1 col-6 bg-light p-4">
                    <h3 class="bg-warning text-info">View Faculty</h3>



                </div>
                <!--View Faculty End Here-->

            </div>
        </section>

    {% else %}


        {{ block.super }}
        <div class="jumbotron jumbotron-fluid text-center">
            <h2 class="display-4">Session Expired !!!</h2>
            <a href="{% url 'myadmin:admin_login' %}" class="btn btn-warning">Login Again</a>
        </div>

    {% endif %}

{% endblock common %}

templates/myadmin/login_success.html
{% extends 'myadmin/base.html' %}
{% load static %}

{% block title%}Success{% endblock title %}
{% block style %}

{% endblock style %}


{% block common %}

    {% if request.session.status %}

        {% include 'myadmin/navbar.html' %}
        <div class="container-fluid">
            <div class="row text-center">
                <div class="offset-2 col-8">
                    <h1>Welcome To Admin</h1>
                    <img src="{% static 'images/matrix-2503236_1920.jpg' %}" class="w-100">
                </div>
            </div>
        </div>

    {% else %}


        {{ block.super }}
        <div class="jumbotron jumbotron-fluid text-center">
            <h2 class="display-4">Session Expired !!!</h2>
            <a href="{% url 'myadmin:admin_login' %}" class="btn btn-warning">Login Again</a>
        </div>

    {% endif %}

{% endblock common %}

templates/myadmin/navbar.html
<!--Navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-info">
            <div >
                <a class="navbar-brand" href="{% url 'myadmin:login_success' %}">E-Learn</a>
            </div>
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarContent">
                <span class="navbar-toggler-icon"></span>
            </button>

            <ul class="collapse navbar-nav navbar-collapse" id="navbarContent">
                <li class="nav-item"><a class="nav-link">{{ admin_data.username|capfirst }}</a></li>
                <li class="nav-item"><a href="{% url 'myadmin:schedule_new_batches' %}" class="nav-link">Schedule New Batches</a></li>
                <li class="nav-item"><a href="{% url 'myadmin:view_scheduled_batches' %}" class="nav-link">New Batches</a></li>
                <li class="nav-item"><a href="{% url 'myadmin:add_course' %}" class="nav-link">Add Courses</a></li>
                <li class="nav-item"><a class="nav-link">View Courses</a></li>
                <li class="nav-item"><a href="{% url 'myadmin:faculty' %}" class="nav-link">Faculty</a></li>
                <li class="nav-item"><a href="{% url 'myadmin:admin_logout' %}" class="nav-link">Logout</a></li>
            </ul>
        </nav>

templates/myadmin/schedule_new_batches.html
{% extends 'myadmin/base.html' %}
{% block title%}Success{% endblock title %}
{% block style %}

{% endblock style %}


{% block common %}

    {% if request.session.status %}

        {% include 'myadmin/navbar.html' %}
        <div class="container my-5">
        <div class="row text-center">
            <div class="offset-md-3 col-md-6 bg-light p-4">
                <h3 class="bg-success">SCHEDULE NEW BATCH</h3>
                <form class="form-group my-4 p-4" action="{% url 'myadmin:schedule_new_batches' %}" method="post">
                    {% csrf_token %}
                    {{ ScheduleBatchForm.as_p }}
                    <div class="btn-group btn-toolbar my-3 p-4">
                        <button type="submit" class="btn btn-outline-success">SCHEDULE</button>
                        <button type="reset" class="btn btn-outline-danger">RESET</button>
                    </div>
                    {% for msg in messages %}
                        <label class="alert alert-success">{{ msg }}</label>
                    {% endfor %}

                </form>
            </div>
        </div>
    </div>

    {% else %}


        {{ block.super }}
        <div class="jumbotron jumbotron-fluid text-center">
            <h2 class="display-4">Session Expired !!!</h2>
            <a href="{% url 'myadmin:admin_login' %}" class="btn btn-warning">Login Again</a>
        </div>

    {% endif %}

{% endblock common %}

templates/myadmin/update_batch.html
{% extends 'myadmin/base.html' %}
{% block title%}Success{% endblock title %}
{% block style %}

{% endblock style %}


{% block common %}

    {% if request.session.status %}

        {% include 'myadmin/navbar.html' %}
        <div class="container my-5">
        <div class="row text-center">
            <div class="offset-md-3 col-md-6 bg-light p-4">
                <h3 class="bg-success">Update Schedule</h3>
                <form class="form-group my-4 p-4" method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div class="btn-group btn-toolbar my-3 p-4">
                        <button type="submit" class="btn btn-outline-success">Update</button>
                        <button type="reset" class="btn btn-outline-danger">RESET</button>
                    </div>
                    {% for msg in messages %}
                        <label class="alert alert-success">{{ msg }}</label>
                    {% endfor %}

                </form>
            </div>
        </div>
    </div>

    {% else %}


        {{ block.super }}
        <div class="jumbotron jumbotron-fluid text-center">
            <h2 class="display-4">Session Expired !!!</h2>
            <a href="{% url 'myadmin:admin_login' %}" class="btn btn-warning">Login Again</a>
        </div>

    {% endif %}

{% endblock common %}

templates/myadmin/view_scheduled_batches.html
{% extends 'myadmin/base.html' %}
{% block title%}Success{% endblock title %}
{% block style %}

{% endblock style %}


{% block common %}

    {% if request.session.status %}

        {% include 'myadmin/navbar.html' %}
        <div class="container-fluid my-5">
        <div class="row text-center">
            <div class="offset-1 col-10 bg-light p-4">
                <h3 class="bg-success">New Batches | Course Schedule | Batch Timings</h3>

                    <table class="table table-hover table-striped table-responsive-lg">
                        <thead class="thead-light">
                            {% for msg in messages %}
                            <tr>
                            <th colspan="9"><label class="alert alert-success">{{ msg }}</label></th>
                            </tr>
                            {% endfor %}

                            <tr>
                                <th>Course</th>
                                <th>Faculty</th>
                                <th>Type</th>
                                <th>Duration</th>
                                <th>Fee</th>
                                <th>Date</th>
                                <th>Time</th>
                                <th>Update</th>
                                <th>Delete</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for batch in view %}
                            <tr>
                                <td>{{ batch.course_name }}</td>
                                <td>{{ batch.faculty_name }}</td>
                                <td>{{ batch.batch_type }}</td>
                                <td>{{ batch.duration }}</td>
                                <td>{{ batch.fee }}</td>
                                <td>{{ batch.start_date }}</td>
                                <td>{{ batch.time }}</td>
                                <td><a href="{% url 'myadmin:update_batch' batch.idno %}" class="btn btn-outline-primary">Update</a></td>
                                <td><a href="{% url 'myadmin:delete_batch' batch.idno %}" class="btn btn-outline-danger">Delete</a></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                        <tfoot></tfoot>
                    </table>


            </div>
        </div>
    </div>

    {% else %}


        {{ block.super }}
        <div class="jumbotron jumbotron-fluid text-center">
            <h2 class="display-4">Session Expired !!!</h2>
            <a href="{% url 'myadmin:admin_login' %}" class="btn btn-warning">Login Again</a>
        </div>

    {% endif %}

{% endblock common %}